# Generated by Django 5.1.1 on 2024-10-03 07:03

from django.db import migrations


def create_games(apps, schema_editor):
    Game = apps.get_model('reviews', 'Game')
    game_titles = [
        "The Legend of Zelda: Breath of the Wild",
        "Super Mario Odyssey",
        "Red Dead Redemption 2",
        "God of War",
        "The Witcher 3: Wild Hunt",
        "Senua's Saga: Hellblade II",
        "Black Myth: Wukong",
        "The Casting of Frank Stone",
        "Star Wars: Outlaws",
        "Warhammer 40,000: Space Marine II",
        "Microsoft Flight Simulator 2024",
        "Half-Life: Through the City",
        "Kingdom Come: Deliverance II",
        "Cyberpunk 2077: Phantom Liberty",
        "Baldur's Gate 3",
        "Avatar: Frontiers of Pandora",
        "Indiana Jones",
        "The Legend of Zelda: Tears of the Kingdom",
        "Redfall",
        "Resident Evil 9",
        "The Elder Scrolls VI",
        "Ghostwire: Tokyo",
        "Hades 2",
        "Hollow Knight: Silksong",
        "Sea of Thieves: Heart of the Flame",
        "Vampire Survivors",
        "Dark and Darker",
        "Stray",
        "Fortnite Chapter 4",
        "League of Legends: Wild Rift",
        "Apex Legends: Respawn",
        "Counter-Strike 2",
        "Overwatch 2",
    ]

    for title in game_titles:
        Game.objects.create(title=title)

class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_game_remove_review_game_title_review_game'),
    ]

    operations = [
        migrations.RunPython(create_games),
    ]
